// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mvc_EntityFrame.Models;

namespace Mvc_EntityFrame.Migrations
{
    [DbContext(typeof(AlunoContext))]
    [Migration("20190206203432_IncluirEntidade_TipoSocio")]
    partial class IncluirEntidade_TipoSocio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Mvc_EntityFrame.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<DateTime>("Nascimento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<int?>("TipoSocioId");

                    b.HasKey("Id");

                    b.HasIndex("TipoSocioId");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Mvc_EntityFrame.Models.TipoSocio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DuracaoEmMeses");

                    b.Property<int>("TaxaDesconto");

                    b.HasKey("Id");

                    b.ToTable("TipoSocios");
                });

            modelBuilder.Entity("Mvc_EntityFrame.Models.Aluno", b =>
                {
                    b.HasOne("Mvc_EntityFrame.Models.TipoSocio", "TipoSocio")
                        .WithMany()
                        .HasForeignKey("TipoSocioId");
                });
#pragma warning restore 612, 618
        }
    }
}
